/**
 * Validation scoring harness — grades the JS engine against the measured
 * anchor datasets in validation/anchors.json (see
 * docs/research/validation-anchors-2026-08-03.md for provenance).
 *
 * Usage:
 *   node validation/score.mjs               # classic model (flag off) scorecard to stdout
 *   node validation/score.mjs --supersonic  # score with the supersonicAero flag ON
 *   node validation/score.mjs --strict      # exit 1 if any gate point fails
 *
 * Requires the engine to be built first (`npm run build`, or
 * `npm run build -w @online-openrocket/engine`).
 *
 * Baseline expectation (classic Extended Barrowman, pre-supersonic-build):
 * supersonic CP series FAIL on every fixture — body CP is frozen at its
 * Mach-1 value in the kernel. That failure is the point of this harness;
 * each build phase should turn rows green without breaking the others.
 */
import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
// Drive the vendored TeaVM engine directly (no TS wrapper build needed). Install the stdout
// sinks the kernel reads once at evaluation, then adapt the handful of facade calls score uses.
globalThis.$rt_putStdoutCustom ??= () => {};
globalThis.$rt_putStderrCustom ??= () => {};
const engine = await import(
  pathToFileURL(join(here, '..', '..', 'web', 'src', 'engine', 'vendor', 'openrocket-engine.mjs')).href
);
const resetEngine = () => engine.reset();
class OrkRocket {
  #h;
  constructor(h) { this.#h = h; }
  static buildTree(tree) { return new OrkRocket(engine.buildRocket(JSON.stringify(tree))); }
  setSupersonicAero(on) { engine.setSupersonicAero(this.#h, on); }
  staticInfo() { return JSON.parse(engine.getStaticInfo(this.#h)); }
  aeroSweep(opts) { return JSON.parse(engine.getAeroSweep(this.#h, JSON.stringify(opts))); }
}

const anchors = JSON.parse(readFileSync(join(here, 'anchors.json'), 'utf8'));
const strict = process.argv.includes('--strict');
// A ratchet, so this can be wired into CI while the absolute score is still low.
// --min <n> fails if the gate score drops BELOW a recorded floor; --expect-gates
// <n> fails if the number of gated points is not exactly n, which is what
// catches a silently shrunken anchors.json (see the gateTotal check below).
const numArg = (flag) => {
  const i = process.argv.indexOf(flag);
  if (i < 0) return null;
  const v = Number(process.argv[i + 1]);
  if (!Number.isInteger(v) || v < 0) {
    console.error(`score: ${flag} needs a non-negative integer`);
    process.exit(2);
  }
  return v;
};
const minPass = numArg('--min');
const expectGates = numArg('--expect-gates');
const supersonic = process.argv.includes('--supersonic');

/** Linear interpolation of series y over grid xs at x (clamped to range). */
function interp(xs, ys, x) {
  if (x <= xs[0]) return ys[0];
  if (x >= xs[xs.length - 1]) return ys[ys.length - 1];
  let i = 1;
  while (xs[i] < x) i++;
  const t = (x - xs[i - 1]) / (xs[i] - xs[i - 1]);
  return ys[i - 1] + t * (ys[i] - ys[i - 1]);
}

const DEG_PER_RAD = 57.29577951308232;
let gateTotal = 0;
let gatePass = 0;
const out = [];
out.push(`# Anchor scorecard — ${supersonic ? 'SUPERSONIC AERO model (flag on)' : 'classic Extended Barrowman (flag off)'}`);
out.push('');
out.push(`Generated by validation/score.mjs. Quantities: cd = drag coefficient (base included/excluded per series), cpPctL = CP as % of body length from nose, cpOverL = CP/length, cnaPerRad / cnaPerDeg = normal-force slope. gate=false rows are informational.`);
out.push('');

for (const [name, spec] of Object.entries(anchors)) {
  if (name.startsWith('_')) continue;
  resetEngine();
  const tree = JSON.parse(readFileSync(join(here, 'fixtures', spec.fixture), 'utf8'));
  const rocket = OrkRocket.buildTree(tree);
  if (supersonic) rocket.setSupersonicAero(true);
  const info = rocket.staticInfo();
  // The fixture says what it is, and the kernel has to agree before a single
  // anchor is scored. Without this a corrupt fixture (a nose length of "abc",
  // null, or 1e999) built a DIFFERENT rocket through the kernel's defaults and
  // scored it as the published model: indistinguishable from a one-gate
  // physics regression. 5e-4 m absorbs the 4-decimal rounding of the recorded
  // values and nothing else.
  const expect = tree._expect;
  if (!expect || !Number.isFinite(expect.length) || !Number.isFinite(expect.refDiameter)) {
    console.error(`score: fixture ${spec.fixture} carries no _expect {length, refDiameter}.`);
    console.error('score:   every fixture must say what the kernel should build from it.');
    process.exit(1);
  }
  for (const key of ['length', 'refDiameter']) {
    if (!(Math.abs(info[key] - expect[key]) <= 5e-4)) {
      console.error(`score: fixture ${spec.fixture} built ${key} = ${info[key]}, expected ${expect[key]}.`);
      console.error('score:   the fixture is corrupt, or the kernel no longer reads it the same way.');
      process.exit(1);
    }
  }
  const sweep = rocket.aeroSweep({
    machMin: 0.05, machMax: spec.maxMach ?? 10, machStep: 0.025,
    aoaDeg: spec.aoaDeg ?? 0, machAlt: spec.machAlt,
  });
  const scale = spec.refAreaScale ?? 1;

  out.push(`## ${name} — ${tree.name}`);
  out.push('');
  out.push(`Length ${info.length.toFixed(4)} m, kernel ref diameter ${info.refDiameter.toFixed(4)} m, dataset ref-area scale x${scale}.`);
  out.push('');

  const model = (series, mach) => {
    switch (series.quantity) {
      case 'cd': {
        let cd = interp(sweep.machs, sweep.powerOff.total, mach);
        if (series.base === 'excluded') cd -= interp(sweep.machs, sweep.powerOff.base, mach);
        return cd * scale;
      }
      case 'cpPctL':
        return (interp(sweep.machs, sweep.cp, mach) / info.length) * 100;
      case 'cpOverL':
        return interp(sweep.machs, sweep.cp, mach) / info.length;
      case 'cnaPerRad':
        return interp(sweep.machs, sweep.cna, mach) * scale;
      case 'cnaPerDeg':
        return (interp(sweep.machs, sweep.cna, mach) * scale) / DEG_PER_RAD;
      default:
        throw new Error(`unknown quantity ${series.quantity}`);
    }
  };

  for (const series of spec.series) {
    out.push(`### ${series.id} (${series.quantity}${series.base ? `, base ${series.base}` : ''})`);
    out.push('');
    out.push(`_${series.source}_`);
    out.push('');
    out.push('| Mach | anchor | model | delta | tol | result |');
    out.push('|---|---|---|---|---|---|');
    for (const [mach, anchor] of series.points) {
      const m = model(series, mach);
      const tol = series.relTol != null ? Math.abs(anchor) * series.relTol : series.tol;
      const delta = m - anchor;
      const inTol = Math.abs(delta) <= tol;
      const gated = series.gate
        && (series.gateMaxMach == null || mach <= series.gateMaxMach)
        && (series.gateMinMach == null || mach >= series.gateMinMach);
      if (gated) {
        gateTotal++;
        if (inTol) gatePass++;
      }
      const result = gated ? (inTol ? 'PASS' : '**FAIL**') : (inTol ? 'ok (info)' : 'off (info)');
      out.push(`| ${mach} | ${anchor} | ${m.toFixed(4)} | ${delta >= 0 ? '+' : ''}${delta.toFixed(4)} | ±${tol.toFixed(4)} | ${result} |`);
    }
    out.push('');
  }
}

out.push('## Summary');
out.push('');
const pct = gateTotal ? `${((100 * gatePass) / gateTotal).toFixed(1)}%` : 'n/a';
out.push(`**Gate points: ${gatePass}/${gateTotal} within tolerance** (${pct}). Informational rows excluded.`);
out.push('');
console.log(out.join('\n'));

// An empty gate set is a BROKEN HARNESS, not a perfect score. `--strict` used to
// pass on it, because `gatePass < gateTotal` is `0 < 0`: a truncated or
// half-written anchors.json scored `0/0 (NaN%)` and exited 0. This runs
// unconditionally, not only under --strict, because a scorecard reporting
// success over nothing is wrong however it was invoked.
if (gateTotal === 0) {
  console.error('score: NO gated points were scored. anchors.json is empty, truncated, or');
  console.error('score:   has every `gate` flag off. That is a broken harness, not a pass.');
  process.exit(1);
}

let failed = false;
// Silent shrinkage of the anchor set is the other way this fails open: the
// denominator just gets smaller and the scorecard reads normally. Pin it.
if (expectGates != null && gateTotal !== expectGates) {
  console.error(`score: expected ${expectGates} gated point(s), scored ${gateTotal}.`);
  console.error('score:   anchors.json changed shape. If deliberate, update --expect-gates.');
  failed = true;
}
if (minPass != null && gatePass < minPass) {
  console.error(`score: gate score ${gatePass}/${gateTotal} is below the recorded floor of ${minPass}.`);
  console.error('score:   the aero model regressed against the published anchors.');
  failed = true;
}
if (strict && gatePass < gateTotal) failed = true;
if (failed) process.exit(1);
