import { useEffect, useMemo, useRef, useState } from 'react';
import { createPortal } from 'react-dom';
import { useTranslation } from 'react-i18next';
import type { ComponentNode, ComponentPosition, RocketTree, StaticInfo } from '../../engine/openRocketEngine';
import { num } from '../../tree/nodeProps';
import { fmtNum } from '../../i18n/format';
import { anchorStarts, axialLength, offsetForStart, snapStart, startFromPosition } from '../../tree/position.js';
import { clusterOffsets } from '../../tree/cluster.js';
import { tubeFinRadius } from '../../tree/tubefins.js';
import { DISPLAY_NAME } from '../../tree/schema.js';
import {
  assemblyBoundingRadius, assemblyChainLength, isAssembly,
  resolveAssemblyRadius, ringInstanceOffsets,
} from '../../tree/assembly.js';
import {
  downloadBlob, IMAGE_FORMAT_EXT, schematicSvg, svgToImage, type ExportData,
} from '../../services/schematicExport.js';
import { ImageExportMenu } from './ImageExportMenu.js';
import { stabilityState, type StabilityState } from '../../services/simReport.js';
import {
  axialStart, calloutLayout, CALLOUT_LANES, collect, finTabFront, MARKER_R,
  niceStep, profilePath, snapNear, type Ctx,
} from './schematicGeometry';

/**
 * 2D side view generated by walking the component tree. Symmetric top-level
 * components (nose/transition/body) form the axial chain; children draw on
 * or inside their parent at their resolved axial position and can be DRAGGED
 * axially (snapping to structural anchors — tube ends, sibling edges).
 * Clustered inner tubes draw one outline per cluster position.
 * CG/CP markers use standard rocketry symbols.
 */

const fillOf = (n: ComponentNode, dflt: string): string =>
  typeof n['color'] === 'string' ? (n['color'] as string) : dflt;

/** Client px a press may wander before it counts as a pan rather than a click.
 *  Matches the drag threshold in onMove — a physical click jitters 1-3 px. */
const PAN_SLOP = 4;

/** Height (viewBox px) reserved at the bottom for the length ruler (side view). */
const RULER_H = 16;
/** Width (viewBox px) reserved on the right for the radial (cross-section) ruler. */
const RULER_W = 26;

/** Same tiered glyphs/vocabulary as StatTiles / SimResults. */
const STABILITY_GLYPH: Record<StabilityState, string> = { under: '⚠', over: '△', ok: '✓' };
const STABILITY_VAR: Record<StabilityState, string> = {
  under: 'var(--status-serious)', over: 'var(--status-warn)', ok: 'var(--status-good)',
};

interface DragState {
  childId: string;
  parent: ComponentNode;
  child: ComponentNode;
  pLen: number;
  /** parent-relative start at pointer-down (m) */
  relStart: number;
  pointerX: number;
  /** viewBox px per client px */
  clientScale: number;
}

export function TreeSchematic({ tree, info, motors, onPatchNode, maxHeight = 480, selectedId, onSelect, exportData, onError, vertical, fillHeight, roll = 0, onRoll, controlsSlot, showMarkers = true }: {
  tree: RocketTree;
  info: StaticInfo | null;
  /** Loaded motor case dimensions (m) keyed by mount node id — drawn to
   *  scale; `label` is the designation printed in the case when it fits (S5). */
  motors?: Record<string, { length: number; diameter: number; label?: string }>;
  onPatchNode?: (id: string, patch: Partial<ComponentNode>) => void;
  /** Cap on the drawing's on-screen height (px). */
  maxHeight?: number;
  /** Two-way selection sync with the component tree (2026-08-05b #21). */
  selectedId?: string | null;
  onSelect?: (id: string) => void;
  /** When set, ⬇ SVG / ⬇ PNG export buttons appear (issue 2026-08-11a). */
  exportData?: Omit<ExportData, 'spanM'>;
  /**
   * Reports an export failure to the caller's note channel. Rasterising really
   * can fail — svgToImage rejects from img.onerror, and a big rocket at 7680px
   * can exhaust the canvas — and the awaited rejection used to go nowhere: the
   * button just did nothing, which reads as "the export is broken" with
   * nothing to report.
   */
  onError?: (message: string) => void;
  /** Nose-up view (S1 rotate / S4 phone): the horizontal layout rotates as
   *  one group to fit the container's HEIGHT. Read-mostly — drag, pan, zoom
   *  and the export/zoom controls are off; hover and click-select stay. */
  vertical?: boolean;
  /** Hero canvas (batch 08-21e): the drawing surface spans the container's
   *  FULL height instead of the adaptive content height — otherwise the svg's
   *  invisible clip edges sit mid-canvas and a zoomed rocket "slides under"
   *  what reads as a black box. Ignored in vertical mode (which fills by its
   *  own rule); overrides maxHeight. */
  fillHeight?: boolean;
  /** Roll angle (radians) about the rocket's long axis — spins the fin sets so
   *  each fin projects by cos(roll + i·2π/N), like OpenRocket's rotation. */
  roll?: number;
  /** When set, a horizontal drag on the drawing spins the roll (delta radians)
   *  instead of panning — so the user can drag to rotate the rocket. */
  onRoll?: (deltaRadians: number) => void;
  /** When set, the drawing's control buttons (calipers, zoom, export) render into
   *  this element (a slot in the pane header) instead of over the drawing. */
  controlsSlot?: HTMLElement | null;
  /** Draw the CG/CP/margin markers and callouts (default true). */
  showMarkers?: boolean;
}) {
  const svgRef = useRef<SVGSVGElement>(null);
  const wrapRef = useRef<HTMLDivElement>(null);
  const drag = useRef<DragState | null>(null);
  // True once the current gesture moved far enough to be a drag — a click
  // that follows a real drag must not change the selection.
  const dragMoved = useRef(false);
  // Container width (CSS px). The viewBox adopts it 1:1, so the drawing fills
  // the column at native pixel scale on any monitor instead of a fixed 640px
  // canvas stretched to fit.
  const [cw, setCw] = useState(640);
  // Container height (CSS px) — the length axis in vertical mode. Stays at
  // the fallback when the wrap has no definite height to inherit.
  const [chPx, setChPx] = useState(480);
  // Hovered component (S5): accent wash + name tag drawn topmost. Enter/
  // leave never fire from touch, so phones skip hover naturally.
  const [hoverId, setHoverId] = useState<string | null>(null);
  // View transform (zoom & pan) in viewBox px; identity = whole rocket fits.
  const [zoom, setZoom] = useState({ k: 1, x: 0, y: 0 });
  // Calipers (measure tool): horizontal (two vertical lines, model x) and/or
  // vertical (two horizontal lines, radial offset from the centreline). null = off.
  const [caliperH, setCaliperH] = useState<{ a: number; b: number } | null>(null);
  const [caliperV, setCaliperV] = useState<{ a: number; b: number } | null>(null);
  const caliperDrag = useRef<{ axis: 'h' | 'v'; end: 'a' | 'b' } | null>(null);
  const { t } = useTranslation();
  // `active` only becomes true once the pointer has travelled past PAN_SLOP —
  // see beginPan for why a press must not pan until then.
  const pan = useRef<
    { pointerX: number; pointerY: number; x0: number; y0: number; active: boolean } | null
  >(null);

  // --- measure the axial chain (memoized) ---
  // Pure geometry derived from the tree, info and container size, so the
  // frequently-changing state (hover, zoom, calipers, roll) no longer
  // recomputes the whole layout on every render.
  const layout = useMemo(() => {
  // Stages flatten into one nose-to-tail chain (sustainer first, boosters
  // after — the desktop's stacking order); legacy flat trees pass through.
  const chain = tree.components.flatMap((n) => (n.type === 'stage' ? n.children ?? [] : [n]));
  let totalLen = 0;
  let maxR = 0.001;
  for (const n of chain) {
    if (n.type === 'nosecone' || n.type === 'bodytube' || n.type === 'transition') {
      totalLen += num(n, 'length', 0);
      maxR = Math.max(maxR, num(n, 'aftRadius', 0), num(n, 'outerRadius', 0), num(n, 'foreRadius', 0));
    }
  }
  // A fin set's vertical span: freeform fins carry no 'height' key — their
  // reach is the outline's y-max (the 0.03 default clipped tall freeform fins
  // out of the adaptive-height frame).
  const finSpan = (n: ComponentNode): number => {
    if (!n.type.endsWith('finset')) return 0;
    if (n.type === 'freeformfinset') {
      const pts = n['points'];
      if (Array.isArray(pts) && pts.length > 0) {
        return Math.max(0, ...pts.map((p) => (Array.isArray(p) ? Number(p[1]) || 0 : 0)));
      }
    }
    // Tube fins reach one tube diameter above the body surface.
    if (n.type === 'tubefinset') return 2 * tubeFinRadius(n, maxR);
    return num(n, 'height', 0.03);
  };
  const protuberanceSpan = (n: ComponentNode): number =>
    (n.type === 'fairing' ? num(n, 'height', 0.02) : 0);
  const finH = Math.max(
    0,
    ...collect(tree.components, finSpan),
    ...collect(tree.components, protuberanceSpan),
  );
  totalLen = Math.max(totalLen, 0.05);

  // Vertical half-extent (m): the core body + fins, plus any off-axis pod's
  // reach (its centerline radius + its own body + its fins) so pods don't clip.
  let vHalf = maxR + finH;
  const scanRadial = (nodes: ComponentNode[], parentR: number) => {
    for (const n of nodes) {
      if (isAssembly(n.type)) {
        const podFin = Math.max(0, ...collect(n.children ?? [], finSpan));
        vHalf = Math.max(vHalf, resolveAssemblyRadius(n, parentR) + assemblyBoundingRadius(n) + podFin);
        scanRadial(n.children ?? [], assemblyBoundingRadius(n));
      } else {
        const r = Math.max(num(n, 'aftRadius', 0), num(n, 'outerRadius', 0), num(n, 'foreRadius', 0)) || parentR;
        scanRadial(n.children ?? [], r);
      }
    }
  };
  scanRadial(chain, maxR);

  // Caliper snap targets: axial component + child edges (horizontal), and radial
  // magnitudes — each component's radius, the body, the full span (vertical).
  const snapXs: number[] = [];
  const radialSet = new Set<number>([0, maxR, vHalf]);
  {
    let cx = 0;
    for (const n of chain) {
      if (n.type === 'nosecone' || n.type === 'bodytube' || n.type === 'transition') {
        const len = num(n, 'length', 0);
        snapXs.push(cx, cx + len);
        for (const child of n.children ?? []) {
          const clen = axialLength(child);
          if (clen > 0) { const cs = axialStart(child, clen, cx, len); snapXs.push(cs, cs + clen); }
        }
        const r = Math.max(num(n, 'aftRadius', 0), num(n, 'outerRadius', 0), num(n, 'foreRadius', 0));
        if (r > 0) radialSet.add(r);
        cx += len;
      }
    }
  }
  const radialSnaps = [...radialSet];

  // Vertical mode swaps the container roles BEFORE layout: all layout math
  // stays horizontal (length along x) and the finished drawing rotates
  // nose-up as one group, so the length axis fits the container HEIGHT and
  // the cross extent its width.
  const w = Math.max(320, vertical ? chPx : cw);
  const pad = 26;
  // Height follows the rocket's own proportions (clamped): a long thin
  // rocket gets a wide low band, not a fixed frame of empty sky. When info
  // is present the CG/CP callout lanes need sky of their own, so their
  // allowance is added to the height AND kept out of the vertical fit —
  // otherwise a height-limited short/fat rocket would fill it and clip them.
  const lanes = info ? CALLOUT_LANES : 0;
  // Side view reserves a ruler lane at the bottom (length) and on the right
  // (radial cross-section), both kept out of the fit.
  const rulerLane = vertical ? 0 : RULER_H;
  const rulerW = vertical ? 0 : RULER_W;
  const crossCap = vertical ? Math.max(160, cw) : maxHeight;
  const h = vertical || !fillHeight
    ? Math.round(Math.min(crossCap, Math.max(200, 2 * vHalf * ((w - 2 * pad) / totalLen) + 2 * pad + lanes + rulerLane)))
    : Math.max(200, chPx);
  // Horizontal headroom: `totalLen` covers only the axial chain (nose+body), so
  // aft-swept fins overhang past it and the CG/CP labels reach right of the aft.
  // Fit to ~12% more than the bare length so nothing sits flush to the edge, and
  // centre the drawing so the margin is even on both sides.
  const scale = Math.min((w - 2 * pad - rulerW) / (totalLen * 1.12), (h - 2 * pad - lanes - rulerLane) / (2 * vHalf));
  // Centre the rocket in the area LEFT of the right ruler lane.
  const x0 = Math.max(pad, (w - rulerW - totalLen * scale) / 2);
  // Centre the rocket in the area ABOVE the bottom ruler lane.
  const ctx: Ctx = { scale, cy: (h - rulerLane) / 2, x0 };
  return { chain, totalLen, maxR, vHalf, snapXs, radialSnaps, rulerLane, w, h, scale, ctx };
  }, [tree, info, vertical, chPx, cw, maxHeight, fillHeight]);
  const { chain, totalLen, maxR, vHalf, snapXs, radialSnaps, rulerLane, w, h, scale, ctx } = layout;

  const beginDrag = (child: ComponentNode, parent: ComponentNode, pLen: number) =>
    (e: React.PointerEvent) => {
      if (!onPatchNode || !child.id) return;
      const rect = svgRef.current?.getBoundingClientRect();
      if (!rect || rect.width === 0) return;
      e.stopPropagation(); // don't also start a background pan
      dragMoved.current = false;
      const pos = (child.position ?? { method: 'top', offset: 0 }) as ComponentPosition;
      drag.current = {
        childId: child.id,
        parent,
        child,
        pLen,
        relStart: startFromPosition(pos, axialLength(child), pLen),
        pointerX: e.clientX,
        clientScale: w / rect.width,
      };
      (e.currentTarget as Element).setPointerCapture?.(e.pointerId);
    };

  /**
   * Clears the "this press became a drag" latch at the START of every press.
   * Attached in the CAPTURE phase on the svg so it runs whatever was pressed,
   * and in vertical mode too. It used to be cleared only inside beginDrag,
   * which is attached to draggable CHILDREN alone — so once any drag passed
   * the 4 px threshold the flag stayed set, and the axial chain (nose cone,
   * body tube, transition) has no pointerdown handler of its own to clear it.
   * Clicking those became a permanent no-op while children kept working.
   */
  const resetDragLatch = () => { dragMoved.current = false; };

  /**
   * Arms a background pan — but does NOT start one, and deliberately does not
   * capture the pointer yet.
   *
   * This handler runs for every press that reaches the svg, which is every
   * press on the axial chain (nose cone, body tube, transition): only
   * draggable CHILDREN stopPropagation in beginDrag. It used to pan on the
   * very first pointermove and capture the pointer immediately, so the 1-3 px
   * of jitter in an ordinary physical click dragged the whole drawing out from
   * under the pointer between press and release. The click then landed on the
   * <svg> instead of the shape and selecting those parts did nothing at all —
   * while children stayed fine, and the vertical view (which attaches neither
   * handler) worked perfectly. Capturing on press made it worse by retargeting
   * the release as well.
   *
   * Both now wait for real movement, so a click stays a click.
   */
  const beginPan = (e: React.PointerEvent) => {
    const rect = svgRef.current?.getBoundingClientRect();
    if (!rect || rect.width === 0) return;
    pan.current = { pointerX: e.clientX, pointerY: e.clientY, x0: zoom.x, y0: zoom.y, active: false };
  };

  /** Screen clientX → model x (metres), through the current pan/zoom. */
  const clientToModelX = (clientX: number): number => {
    const rect = svgRef.current?.getBoundingClientRect();
    if (!rect || !rect.width) return 0;
    const viewBoxX = ((clientX - rect.left) / rect.width) * w;
    return ((viewBoxX - zoom.x) / zoom.k - ctx.x0) / scale;
  };
  /** Screen clientY → radial offset from the centreline (metres, + up). */
  const clientToModelY = (clientY: number): number => {
    const rect = svgRef.current?.getBoundingClientRect();
    if (!rect || !rect.height) return 0;
    const viewBoxY = ((clientY - rect.top) / rect.height) * h;
    return (ctx.cy - (viewBoxY - zoom.y) / zoom.k) / scale;
  };

  const beginCaliperDrag = (axis: 'h' | 'v', end: 'a' | 'b') => (e: React.PointerEvent) => {
    e.stopPropagation(); // don't also start a pan
    caliperDrag.current = { axis, end };
    (e.currentTarget as Element).setPointerCapture?.(e.pointerId);
  };

  const onMove = (e: React.PointerEvent) => {
    if (caliperDrag.current) {
      const { axis, end } = caliperDrag.current;
      const eps = 6 / (scale * zoom.k); // ~6 screen px of snap magnetism
      if (axis === 'h') {
        const mx = Math.max(0, Math.min(totalLen, snapNear(clientToModelX(e.clientX), snapXs, eps)));
        setCaliperH((c) => (c ? { ...c, [end]: mx } : c));
      } else {
        const raw = clientToModelY(e.clientY);
        const mag = snapNear(Math.abs(raw), radialSnaps, eps);
        const my = Math.max(-vHalf, Math.min(vHalf, Math.sign(raw || 1) * mag));
        setCaliperV((c) => (c ? { ...c, [end]: my } : c));
      }
      return;
    }
    const d = drag.current;
    if (d && onPatchNode) {
      if (Math.abs(e.clientX - d.pointerX) > 4) dragMoved.current = true;
      const dxModel = ((e.clientX - d.pointerX) * d.clientScale) / (scale * zoom.k);
      const anchors = anchorStarts(d.parent, d.child);
      const epsilon = 6 / (scale * zoom.k); // ~6 screen px of magnetism
      const snapped = snapStart(d.relStart + dxModel, anchors, epsilon);
      const pos = (d.child.position ?? { method: 'top', offset: 0 }) as ComponentPosition;
      onPatchNode(d.childId, {
        position: {
          method: pos.method,
          offset: offsetForStart(pos.method, snapped, axialLength(d.child), d.pLen),
        },
      });
      return;
    }
    const p = pan.current;
    if (p) {
      const dx = e.clientX - p.pointerX;
      const dy = e.clientY - p.pointerY;
      // Below the slop this press is still a click, not a pan. Once it IS a
      // pan, take the pointer so the gesture survives leaving the svg.
      if (!p.active) {
        if (Math.abs(dx) < PAN_SLOP && Math.abs(dy) < PAN_SLOP) return;
        p.active = true;
        (e.currentTarget as Element).setPointerCapture?.(e.pointerId);
      }
      // Drag-to-roll: horizontal motion spins the fins (~1 turn per width).
      if (onRoll) {
        const r = svgRef.current?.getBoundingClientRect();
        const width = r && r.width ? r.width : 400;
        onRoll((dx / width) * 2 * Math.PI);
        p.pointerX = e.clientX;
        return;
      }
      const rect = svgRef.current?.getBoundingClientRect();
      if (!rect || rect.width === 0) return;
      const clientScale = w / rect.width;
      setZoom((z) => ({ ...z, x: p.x0 + dx * clientScale, y: p.y0 + dy * clientScale }));
    }
  };

  const endDrag = () => { drag.current = null; pan.current = null; caliperDrag.current = null; };

  // Track the container's size so the viewBox can follow it (height feeds
  // the vertical mode's length axis).
  useEffect(() => {
    const el = wrapRef.current;
    if (!el) return;
    const obs = new ResizeObserver(() => {
      if (el.clientWidth > 0) setCw(el.clientWidth);
      if (el.clientHeight > 0) setChPx(el.clientHeight);
    });
    obs.observe(el);
    return () => obs.disconnect();
  }, []);

  // Wheel zoom around the pointer. Native listener: React's onWheel is
  // passive, so preventDefault (to stop page scroll) must be attached here.
  useEffect(() => {
    const svg = svgRef.current;
    if (!svg || vertical) return;
    const onWheel = (e: WheelEvent) => {
      e.preventDefault();
      const rect = svg.getBoundingClientRect();
      if (rect.width === 0) return;
      const px = ((e.clientX - rect.left) / rect.width) * w;
      const py = ((e.clientY - rect.top) / rect.height) * h;
      setZoom((z) => {
        const k = Math.min(12, Math.max(1, z.k * (e.deltaY < 0 ? 1.2 : 1 / 1.2)));
        if (k === z.k) return z;
        // Keep the model point under the cursor fixed while scaling.
        const mx = (px - z.x) / z.k;
        const my = (py - z.y) / z.k;
        const next = { k, x: px - mx * k, y: py - my * k };
        return k === 1 ? { k: 1, x: 0, y: 0 } : next;
      });
    };
    svg.addEventListener('wheel', onWheel, { passive: false });
    return () => svg.removeEventListener('wheel', onWheel);
  }, [w, h, vertical]);

  // Button zoom steps around the view center (the wheel handles precise
  // pointer-anchored zoom; these make the capability visible).
  const zoomBy = (f: number) => setZoom((z) => {
    const k = Math.min(12, Math.max(1, z.k * f));
    if (k === z.k) return z;
    const mx = (w / 2 - z.x) / z.k;
    const my = (h / 2 - z.y) / z.k;
    return k === 1 ? { k: 1, x: 0, y: 0 } : { k, x: w / 2 - mx * k, y: h / 2 - my * k };
  });

  // Selection sync: click any drawn component to select it in the tree; the
  // selected component draws with an accent outline.
  const isSel = (n: ComponentNode) => !!selectedId && n.id === selectedId;
  const clickable = (n: ComponentNode) => ({
    ...(n.id
      ? {
        onPointerEnter: () => setHoverId(n.id!),
        onPointerLeave: () => setHoverId((cur) => (cur === n.id ? null : cur)),
      }
      : {}),
    ...(onSelect && n.id
      ? {
        onClick: (e: React.MouseEvent) => {
          e.stopPropagation();
          if (!dragMoved.current) onSelect(n.id!);
        },
        style: { cursor: 'pointer' } as React.CSSProperties,
      }
      : {}),
  });
  const selStroke = (n: ComponentNode, dflt: string) => (isSel(n) ? 'var(--accent)' : dflt);
  const selWidth = (n: ComponentNode, dflt: number | string = 1) => (isSel(n) ? 2 : dflt);

  // Nose-up rendering rotates the whole drawing; every text label counter-
  // rotates about its own anchor so it still reads horizontally.
  const textUp = (x: number, y: number) =>
    (vertical ? { transform: `rotate(-90 ${x} ${y})` } : {});

  // --- render chain + children ---
  const shapes: React.ReactNode[] = [];
  // Dashed "shadow" shapes (inner components, shoulders) paint AFTER the whole
  // hull: SVG stacks by document order, so a coupler overhanging into the NEXT
  // tube used to vanish under that tube's opaque fill (while the overhang into
  // the PREVIOUS tube, already painted, stayed visible — Eric's ebay report).
  const overlay: React.ReactNode[] = [];
  let key = 0;

  // Hovered component's drawn extent (layout px), unioned across instances
  // (cluster copies, pod rings) as the shapes render.
  const hoverBoxes: { x0: number; y0: number; x1: number; y1: number }[] = [];
  let hoverName = '';
  const noteHover = (n: ComponentNode, x0: number, y0: number, x1: number, y1: number) => {
    if (!hoverId || n.id !== hoverId) return;
    hoverName = n.name ?? DISPLAY_NAME[n.type];
    hoverBoxes.push({
      x0: Math.min(x0, x1), y0: Math.min(y0, y1),
      x1: Math.max(x0, x1), y1: Math.max(y0, y1),
    });
  };

  // Loaded motor case (S5): launch-orange tint at the real case size, with
  // the designation printed in the case when it's long enough to carry it.
  const motorShapes = (
    motor: { length: number; diameter: number; label?: string },
    mStart: number, cY: number,
  ): React.ReactNode[] => {
    const mR = motor.diameter / 2;
    const out: React.ReactNode[] = [
      <rect key={key++} x={ctx.x0 + mStart * ctx.scale} y={cY - mR * ctx.scale}
        width={Math.max(2, motor.length * ctx.scale)} height={Math.max(2, 2 * mR * ctx.scale)}
        rx="1" fill="var(--launch)" fillOpacity="0.85"
        stroke="#e0764a" strokeWidth="0.8"
        style={{ pointerEvents: 'none' }} />,
    ];
    if (motor.label && motor.length * ctx.scale > 36) {
      const lx = ctx.x0 + (mStart + motor.length / 2) * ctx.scale;
      out.push(
        <text key={key++} x={lx} y={cY} textAnchor="middle" dominantBaseline="central"
          fontSize="10" fontWeight="bold" fill="#ffffff" {...textUp(lx, cY)}
          style={{ pointerEvents: 'none' }}>
          {motor.label}
        </text>,
      );
    }
    return out;
  };

  const renderChildren = (parent: ComponentNode, pStart: number, pLen: number, pRadius: number, baseY: number) => {
    for (const child of parent.children ?? []) {
      const t = child.type;
      // Off-axis assembly: draw its whole chain once per ring instance at the
      // instance's projected baseline (side view projects y, ignores depth z).
      if (isAssembly(t)) {
        const podChain = child.children ?? [];
        const podLen = assemblyChainLength(child);
        const podRadius = resolveAssemblyRadius(child, pRadius);
        const podStart = axialStart(child, podLen, pStart, pLen);
        const count = Math.max(1, Math.round(num(child, 'instanceCount', 2)));
        for (const off of ringInstanceOffsets(count, podRadius, num(child, 'angleOffset', 0))) {
          renderChain(podChain, podStart, baseY + off.y * ctx.scale);
        }
        continue;
      }
      const grab = {
        ...clickable(child),
        ...(onPatchNode && child.id && !vertical
          ? {
            onPointerDown: beginDrag(child, parent, pLen),
            style: { cursor: 'grab' } as React.CSSProperties,
          }
          : {}),
      };
      // Through-the-wall fin tab: dashed rect from the body surface inward.
      const renderTab = (finStart: number, finLen: number) => {
        const tabH = Math.min(num(child, 'tabHeight', 0), pRadius);
        const tabLen = num(child, 'tabLength', 0);
        if (tabH <= 0 || tabLen <= 0) return;
        const front = finStart + finTabFront(child, finLen);
        for (const dir of [1, -1] as const) {
          const yTop = dir === 1
            ? baseY + (pRadius - tabH) * ctx.scale
            : baseY - pRadius * ctx.scale;
          shapes.push(
            <rect key={key++} x={ctx.x0 + front * ctx.scale} y={yTop}
              width={Math.max(2, tabLen * ctx.scale)} height={Math.max(1.5, tabH * ctx.scale)}
              fill={fillOf(child, '#b9b7b0')} fillOpacity="0.35"
              stroke="#7a786f" strokeWidth="1" strokeDasharray="3 2"
              style={{ pointerEvents: 'none' }} />,
          );
        }
      };
      if (t === 'freeformfinset') {
        const raw = (child['points'] as [number, number][] | undefined) ?? [];
        if (raw.length >= 3) {
          const chord = Math.max(...raw.map((p) => p[0]));
          const start = axialStart(child, chord, pStart, pLen);
          const ymax = Math.max(0, ...raw.map((p) => p[1]));
          noteHover(child, ctx.x0 + start * ctx.scale, baseY - (pRadius + ymax) * ctx.scale,
            ctx.x0 + (start + chord) * ctx.scale, baseY + (pRadius + ymax) * ctx.scale);
          for (const dir of [1, -1] as const) {
            const ptsStr = raw
              .map(([px, py]) => `${ctx.x0 + (start + px) * ctx.scale},${baseY + dir * (pRadius + py) * ctx.scale}`)
              .join(' ');
            shapes.push(
              <polygon key={key++} points={ptsStr}
                fill={fillOf(child, '#b9b7b0')} stroke={selStroke(child, '#7a786f')}
                strokeWidth={selWidth(child)} {...grab} />,
            );
          }
          renderTab(start, chord);
        }
      } else if (t === 'trapezoidfinset' || t === 'ellipticalfinset') {
        const root = num(child, 'rootChord', 0.05);
        const tip = t === 'trapezoidfinset' ? num(child, 'tipChord', root * 0.6) : 0;
        const sweep = t === 'trapezoidfinset' ? num(child, 'sweep', 0.02) : root / 2;
        const height = num(child, 'height', 0.03);
        const start = axialStart(child, root, pStart, pLen);
        noteHover(child, ctx.x0 + start * ctx.scale, baseY - (pRadius + height) * ctx.scale,
          ctx.x0 + (start + Math.max(root, sweep + tip)) * ctx.scale,
          baseY + (pRadius + height) * ctx.scale);
        // Spin about the axis: each of the N fins projects into the side view
        // by cos(roll + i·2π/N). |cos|=1 → broadside (full height), 0 → edge-on
        // (invisible). Draw edge-on-ish fins last so broadside ones sit on top.
        const finCount = Math.max(1, Math.round(num(child, 'finCount', 3)));
        const projected = Array.from({ length: finCount }, (_, fi) => Math.cos(roll + (fi * 2 * Math.PI) / finCount))
          .filter((p) => Math.abs(p) >= 0.03)
          .sort((a, b) => Math.abs(a) - Math.abs(b));
        for (const proj of projected) {
          const dir = proj >= 0 ? 1 : -1;
          const hp = height * Math.abs(proj);
          const y0 = baseY + dir * pRadius * ctx.scale;
          const yh = baseY + dir * (pRadius + hp) * ctx.scale;
          const X = ctx.x0 + start * ctx.scale;
          shapes.push(
            t === 'trapezoidfinset' ? (
              <polygon key={key++}
                points={`${X},${y0} ${X + sweep * ctx.scale},${yh} ${X + (sweep + tip) * ctx.scale},${yh} ${X + root * ctx.scale},${y0}`}
                fill={fillOf(child, '#b9b7b0')} stroke={selStroke(child, '#7a786f')}
                strokeWidth={selWidth(child)} {...grab} />
            ) : (
              // Elliptical fin = the top half of an ellipse: major axis = root
              // chord (horizontal), semi-minor axis = span. An SVG arc draws it
              // exactly and reaches the FULL span — a quadratic Bézier only bent
              // ~halfway to its control point, drawing the fin at ~half height.
              <path key={key++}
                d={`M ${X} ${y0} A ${(root / 2) * ctx.scale} ${hp * ctx.scale} 0 0 ${dir > 0 ? 1 : 0} ${X + root * ctx.scale} ${y0} Z`}
                fill={fillOf(child, '#b9b7b0')} stroke={selStroke(child, '#7a786f')}
                strokeWidth={selWidth(child)} {...grab} />
            ),
          );
        }
        renderTab(start, root);
      } else if (t === 'tubefinset') {
        // Side view: the top and bottom tubes of the ring, sitting on the
        // body surface (side tubes project onto the body — omitted). Each
        // is drawn as its silhouette rectangle with a center line hinting
        // at the tube bore.
        const len = num(child, 'length', 0.1);
        const rt = tubeFinRadius(child, pRadius);
        const start = axialStart(child, len, pStart, pLen);
        const X = ctx.x0 + start * ctx.scale;
        noteHover(child, X, baseY - (pRadius + 2 * rt) * ctx.scale,
          X + len * ctx.scale, baseY + (pRadius + 2 * rt) * ctx.scale);
        for (const dir of [1, -1] as const) {
          const yNear = baseY + dir * pRadius * ctx.scale;
          const yFar = baseY + dir * (pRadius + 2 * rt) * ctx.scale;
          shapes.push(
            <rect key={key++} x={X} y={Math.min(yNear, yFar)}
              width={Math.max(2, len * ctx.scale)} height={Math.abs(yFar - yNear)}
              rx="2" fill={fillOf(child, '#c8c5be')} fillOpacity="0.6"
              stroke={selStroke(child, '#7a786f')} strokeWidth={selWidth(child)} {...grab} />,
            <line key={key++} x1={X} y1={(yNear + yFar) / 2} x2={X + len * ctx.scale} y2={(yNear + yFar) / 2}
              stroke="#7a786f" strokeWidth="0.8" strokeDasharray="4 3"
              style={{ pointerEvents: 'none' }} />,
          );
        }
      } else if (t === 'fairing') {
        // External shroud: SOLID outline (it's on the outside — Eric's spec),
        // drawn on the top surface; radial angle isn't modeled.
        const len = num(child, 'length', 0.08);
        const hgt = num(child, 'height', 0.02);
        const fshape = String(child['fairingShape'] ?? 'halfround');
        const start = axialStart(child, len, pStart, pLen);
        const X = ctx.x0 + start * ctx.scale;
        const y0 = baseY - pRadius * ctx.scale;
        const yh = y0 - hgt * ctx.scale;
        const Xe = X + len * ctx.scale;
        noteHover(child, X, yh, Xe, y0);
        shapes.push(
          fshape === 'streamlined' ? (
            <polygon key={key++}
              points={`${X},${y0} ${X + 0.3 * len * ctx.scale},${yh} ${X + 0.7 * len * ctx.scale},${yh} ${Xe},${y0}`}
              fill={fillOf(child, '#c8c5be')} stroke={selStroke(child, '#7a786f')}
              strokeWidth={selWidth(child)} {...grab} />
          ) : fshape === 'halfround' ? (
            <path key={key++}
              d={`M ${X} ${y0} L ${X} ${yh + 0.35 * (y0 - yh)} Q ${X} ${yh} ${X + Math.min(8, len * ctx.scale * 0.25)} ${yh} L ${Xe - Math.min(8, len * ctx.scale * 0.25)} ${yh} Q ${Xe} ${yh} ${Xe} ${yh + 0.35 * (y0 - yh)} L ${Xe} ${y0} Z`}
              fill={fillOf(child, '#c8c5be')} stroke={selStroke(child, '#7a786f')}
              strokeWidth={selWidth(child)} {...grab} />
          ) : (
            <rect key={key++} x={X} y={yh}
              width={Math.max(2, len * ctx.scale)} height={Math.max(2, hgt * ctx.scale)}
              fill={fillOf(child, '#c8c5be')} stroke={selStroke(child, '#7a786f')}
              strokeWidth={selWidth(child)} {...grab} />
          ),
        );
      } else if (t === 'launchlug' || t === 'railbutton') {
        // Rail buttons are edited via 'outerDiameter' (their only size field)
        // and have no axial 'length' — a button is about as long as it is wide.
        const btnDia = t === 'railbutton' ? num(child, 'outerDiameter', 0.004) : 0;
        const len = t === 'railbutton' ? btnDia : num(child, 'length', 0.01);
        const r = t === 'railbutton' ? btnDia / 2 : num(child, 'outerRadius', 0.002);
        const start = axialStart(child, len, pStart, pLen);
        // Project the radial mount angle onto the side profile: 0° stands at full
        // height above the tube, ±90° is edge-on (foreshortens away), 180° sits
        // below. Vertical offset = radius·cos(angle) (kernel default 180°).
        const c = Math.cos(num(child, 'angleOffset', Math.PI));
        const yInner = baseY - pRadius * c * ctx.scale;
        const yOuter = baseY - (pRadius + 2 * r) * c * ctx.scale;
        const yTop = Math.min(yInner, yOuter);
        const h = Math.max(1, Math.abs(yOuter - yInner));
        noteHover(child, ctx.x0 + start * ctx.scale, yTop, ctx.x0 + (start + len) * ctx.scale, yTop + h);
        shapes.push(
          <rect key={key++} x={ctx.x0 + start * ctx.scale} y={yTop}
            width={Math.max(2, len * ctx.scale)} height={h}
            fill={fillOf(child, '#c8c5be')} stroke={selStroke(child, '#7a786f')}
            strokeWidth={selWidth(child)} {...grab} />,
        );
      } else {
        // Internal component: dashed outline inside the parent. A clustered
        // inner tube draws once per cluster position (side-view projection).
        // Per-type stroke color + a small tag differentiate what used to be
        // identical grey boxes (issue 2026-08-05a #21) — tubes/couplers stay
        // neutral (they really are tube segments), payload-type parts get
        // muted colors from the theme-safe midrange.
        const TYPE_STYLE: Partial<Record<string, { stroke: string; tag: string }>> = {
          parachute: { stroke: '#b06a35', tag: 'chute' },
          streamer: { stroke: '#a08c2e', tag: 'strmr' },
          shockcord: { stroke: '#8f7a8d', tag: 'cord' },
          masscomponent: { stroke: '#a85f5c', tag: 'mass' },
          centeringring: { stroke: '#6f8a5c', tag: 'CR' },
          bulkhead: { stroke: '#66748c', tag: 'BH' },
          engineblock: { stroke: '#7d7050', tag: 'EB' },
        };
        const style = TYPE_STYLE[child.type];
        const len = num(child, 'length', num(child, 'packedLength', 0.025));
        const r = Math.min(
          pRadius * 0.85,
          num(child, 'outerRadius', num(child, 'radius', num(child, 'packedRadius', pRadius * 0.7))),
        );
        const start = axialStart(child, len, pStart, pLen);
        const offsets = child.type === 'innertube'
          ? clusterOffsets(
            child['cluster'] as string | undefined,
            num(child, 'outerRadius', 0.0095),
            num(child, 'clusterScale', 1),
            num(child, 'clusterRotation', 0),
          )
          : [{ y: 0, z: 0 }];
        // Loaded motor: a brownish silhouette at the REAL case size, seated
        // flush against the mount's aft end (how motors actually load).
        const motor = child.type === 'innertube' && child.id ? motors?.[child.id] : undefined;
        for (const off of offsets) {
          const inkColor = isSel(child) ? 'var(--accent)' : fillOf(child, style?.stroke ?? '#9a978f');
          noteHover(child, ctx.x0 + start * ctx.scale, baseY + (off.y - r) * ctx.scale,
            ctx.x0 + (start + len) * ctx.scale, baseY + (off.y + r) * ctx.scale);
          overlay.push(
            <rect key={key++} x={ctx.x0 + start * ctx.scale}
              y={baseY + (off.y - r) * ctx.scale}
              width={Math.max(2, len * ctx.scale)} height={2 * r * ctx.scale}
              fill={child.type === 'bulkhead' ? 'url(#bulkhead-hatch)' : 'rgba(127,127,127,0.001)'}
              stroke={inkColor} strokeWidth={selWidth(child)}
              strokeDasharray="3 2" {...grab}>
              <title>{child.name ?? DISPLAY_NAME[child.type]}</title>
            </rect>,
          );
          // Miniature glyphs (Eric's pick, 2026-08-05b #21): a picture inside
          // the box for chutes, mass items, centering rings and shock cords,
          // drawn whenever there's room; the text tag stays for the rest.
          const bw = len * ctx.scale;
          const bh = 2 * r * ctx.scale;
          const gcx = ctx.x0 + (start + len / 2) * ctx.scale;
          const gcy = baseY + off.y * ctx.scale;
          const gs = Math.min(bw * 0.8, bh * 0.7); // glyph box size
          if (gs >= 8) {
            const g = gs / 2;
            const glyphProps = { stroke: fillOf(child, style?.stroke ?? '#9a978f'), fill: 'none', strokeWidth: 1.2, style: { pointerEvents: 'none' as const } };
            if (child.type === 'parachute') {
              overlay.push(
                <g key={key++} {...glyphProps}>
                  <path d={`M ${gcx - g} ${gcy} A ${g} ${g} 0 0 1 ${gcx + g} ${gcy}`} />
                  <path d={`M ${gcx - g} ${gcy} L ${gcx} ${gcy + g} L ${gcx + g} ${gcy} M ${gcx - g * 0.45} ${gcy - g * 0.65} L ${gcx} ${gcy + g} M ${gcx + g * 0.45} ${gcy - g * 0.65} L ${gcx} ${gcy + g}`} />
                </g>,
              );
            } else if (child.type === 'masscomponent') {
              overlay.push(
                <g key={key++} {...glyphProps}>
                  <rect x={gcx - g * 0.7} y={gcy - g * 0.35} width={g * 1.4} height={g * 1.05}
                    fill={fillOf(child, style?.stroke ?? '#9a978f')} fillOpacity="0.35" />
                  <path d={`M ${gcx - g * 0.35} ${gcy - g * 0.35} A ${g * 0.4} ${g * 0.5} 0 0 1 ${gcx + g * 0.35} ${gcy - g * 0.35}`} />
                </g>,
              );
            } else if (child.type === 'centeringring') {
              // Ring cross-section: material near the walls, bore in the middle.
              overlay.push(
                <g key={key++} {...glyphProps}>
                  <line x1={gcx} y1={gcy - bh / 2 + 1.5} x2={gcx} y2={gcy - bh * 0.16} strokeWidth={Math.max(2, bw * 0.5)} />
                  <line x1={gcx} y1={gcy + bh * 0.16} x2={gcx} y2={gcy + bh / 2 - 1.5} strokeWidth={Math.max(2, bw * 0.5)} />
                </g>,
              );
            } else if (child.type === 'shockcord') {
              const seg = gs / 4;
              overlay.push(
                <path key={key++} {...glyphProps}
                  d={`M ${gcx - g} ${gcy} ${[1, 2, 3, 4].map((i) => `L ${gcx - g + i * seg * 2 - seg} ${gcy + (i % 2 ? -1 : 1) * g * 0.45} L ${gcx - g + i * seg * 2} ${gcy}`).join(' ')}`} />,
              );
            }
          }
          // Type tag, when the box has room for it — glyph types skip the
          // text once their picture is drawn. Counter-rotated tags read
          // horizontally in vertical mode, so the room roles swap.
          const hasGlyph = gs >= 8
            && ['parachute', 'masscomponent', 'centeringring', 'shockcord'].includes(child.type);
          const tagRoom = vertical
            ? 2 * r * ctx.scale > 26 && len * ctx.scale > 11
            : len * ctx.scale > 26 && 2 * r * ctx.scale > 11;
          if (style && !hasGlyph && tagRoom) {
            const tx = ctx.x0 + (start + len / 2) * ctx.scale;
            const ty = baseY + off.y * ctx.scale;
            overlay.push(
              <text key={key++} x={tx} y={ty}
                textAnchor="middle" dominantBaseline="central"
                fontSize="8.5" fill={fillOf(child, style.stroke)} {...textUp(tx, ty)}
                style={{ pointerEvents: 'none', textTransform: 'uppercase', letterSpacing: '0.04em' }}>
                {style.tag}
              </text>,
            );
          }
          if (motor) {
            overlay.push(...motorShapes(
              motor, start + len - motor.length + num(child, 'motorOverhang', 0),
              baseY + off.y * ctx.scale));
          }
        }
        renderChildren(child, start, len, r, baseY);
      }
    }
  };

  // Dashed outline for a shoulder sliding inside the adjacent tube. Painted in
  // the overlay pass — an aft shoulder lives inside the NEXT tube, which is
  // drawn later and would otherwise cover it.
  const shoulderRect = (startX: number, lenSi: number, rSi: number, color: string, baseY: number) => {
    if (lenSi <= 0 || rSi <= 0) return;
    overlay.push(
      <rect key={key++} x={ctx.x0 + startX * scale} y={baseY - rSi * scale}
        width={Math.max(1.5, lenSi * scale)} height={2 * rSi * scale}
        fill="rgba(127,127,127,0.001)" stroke={color} strokeWidth="1"
        strokeDasharray="3 2" style={{ pointerEvents: 'none' }} />,
    );
  };

  // Draws an axial nose→tail chain with its centerline at screen `baseY`
  // (ctx.cy for the core rocket; offset for each off-axis pod instance).
  const renderChain = (nodes: ComponentNode[], xStart: number, baseY: number) => {
    let cx = xStart;
    for (const n of nodes) {
      const len = num(n, 'length', 0);
      if (n.type === 'nosecone') {
        const r = num(n, 'aftRadius', 0.012);
        noteHover(n, ctx.x0 + cx * scale, baseY - r * scale, ctx.x0 + (cx + len) * scale, baseY + r * scale);
        shapes.push(<path key={key++} d={profilePath(ctx, n, cx, len, 0, r, baseY)} fill={fillOf(n, '#d5d2cb')}
          stroke={selStroke(n, '#7a786f')} strokeWidth={selWidth(n)} {...clickable(n)} />);
        shoulderRect(cx + len, num(n, 'shoulderLength', 0), num(n, 'shoulderRadius', 0), '#9a978f', baseY);
        renderChildren(n, cx, len, r, baseY);
        cx += len;
      } else if (n.type === 'bodytube') {
        const r = num(n, 'outerRadius', 0.012);
        noteHover(n, ctx.x0 + cx * scale, baseY - r * scale, ctx.x0 + (cx + len) * scale, baseY + r * scale);
        shapes.push(
          <rect key={key++} x={ctx.x0 + cx * scale} y={baseY - r * scale}
            width={len * scale} height={2 * r * scale}
            fill={fillOf(n, '#e7e5e0')} stroke={selStroke(n, '#7a786f')}
            strokeWidth={selWidth(n)} {...clickable(n)} />,
        );
        // Min-diameter: a motor loaded directly in this body tube draws at its
        // real case size, seated flush against the tube's aft end.
        const tubeMotor = n.id ? motors?.[n.id] : undefined;
        if (tubeMotor) {
          shapes.push(...motorShapes(
            tubeMotor, cx + len - tubeMotor.length + num(n, 'motorOverhang', 0), baseY));
        }
        renderChildren(n, cx, len, r, baseY);
        cx += len;
      } else if (n.type === 'transition') {
        const rf = num(n, 'foreRadius', 0.012);
        const ra = num(n, 'aftRadius', 0.009);
        noteHover(n, ctx.x0 + cx * scale, baseY - Math.max(rf, ra) * scale,
          ctx.x0 + (cx + len) * scale, baseY + Math.max(rf, ra) * scale);
        shapes.push(
          <path key={key++} d={profilePath(ctx, n, cx, len, rf, ra, baseY)}
            fill={fillOf(n, '#d5d2cb')} stroke={selStroke(n, '#7a786f')}
            strokeWidth={selWidth(n)} {...clickable(n)} />,
        );
        const fsl = num(n, 'foreShoulderLength', 0);
        shoulderRect(cx - fsl, fsl, num(n, 'foreShoulderRadius', 0), '#9a978f', baseY);
        shoulderRect(cx + len, num(n, 'aftShoulderLength', 0), num(n, 'aftShoulderRadius', 0), '#9a978f', baseY);
        renderChildren(n, cx, len, Math.max(rf, ra), baseY);
        cx += len;
      }
    }
  };

  renderChain(chain, 0, ctx.cy);

  // When markers are toggled off, null out the stations: this disables the
  // on-axis symbols AND the leader-line callouts (all gated on cgX/cpX below).
  const cgX = info && showMarkers ? ctx.x0 + info.cg * scale : null;
  const cpX = info && showMarkers ? ctx.x0 + info.cp * scale : null;
  const stab = info ? stabilityState(info.stabilityCalibers) : null;
  const marginPct = info && info.length > 0 ? ((info.cp - info.cg) / info.length) * 100 : null;
  const stabWord = stab === 'under' ? t('schematic.underStable') : stab === 'over' ? t('schematic.overStable') : t('schematic.ok');
  const marginText = info && stab
    ? `${STABILITY_GLYPH[stab]} ${fmtNum(info.stabilityCalibers, 2)} ${t('stability.caliber')} · ${fmtNum(marginPct!, 1)}% — ${stabWord}`
    : null;
  const cgLabel = info ? `${t('schematic.cg')} · ${fmtNum(info.cg * 100, 1)} cm` : t('schematic.cg');
  const cpLabel = info ? `${t('schematic.cp')} · ${fmtNum(info.cp * 100, 1)} cm` : t('schematic.cp');
  const callouts = calloutLayout(cgX, cpX, ctx.cy, vHalf * scale, w, h, marginText);

  // Hover overlay (S5): a light accent wash over the hovered component's
  // extent plus a name tag — deliberately fainter than the solid width-2
  // selection outline so the two stay distinguishable.
  const hoverBox = hoverBoxes.length
    ? hoverBoxes.reduce((a, b) => ({
      x0: Math.min(a.x0, b.x0), y0: Math.min(a.y0, b.y0),
      x1: Math.max(a.x1, b.x1), y1: Math.max(a.y1, b.y1),
    }))
    : null;
  let hoverTag: { x: number; y: number; tw: number } | null = null;
  if (hoverBox) {
    const tw = hoverName.length * 6.2 + 14;
    hoverTag = {
      x: Math.min(w - tw / 2 - 2, Math.max(tw / 2 + 2, (hoverBox.x0 + hoverBox.x1) / 2)),
      // Above the component unless that leaves the viewBox; then below.
      y: hoverBox.y0 - 22 >= 2 ? hoverBox.y0 - 13 : Math.min(h - 11, hoverBox.y1 + 13),
      tw,
    };
  }

  // Dimension ruler (side view, only at the default fit): nice-round marks every
  // `rulerStep` metres, labelled in cm. 0 sits at the nose (the datum) but the
  // baseline + ticks run the FULL viewport width, so it reads as a workbench
  // rule spanning the canvas rather than a bar clipped to the airframe.
  const showRuler = !vertical && zoom.k === 1 && zoom.x === 0 && zoom.y === 0;
  const rulerStep = niceStep(totalLen);
  const rulerX0 = 2; // left inset (viewBox px)
  const rulerX1 = w - 2; // right inset
  const rulerMarks: number[] = [];
  if (showRuler) {
    const mLo = Math.ceil((rulerX0 - ctx.x0) / scale / rulerStep - 1e-6) * rulerStep;
    const mHi = (rulerX1 - ctx.x0) / scale;
    for (let m = mLo; m <= mHi + 1e-6; m += rulerStep) rulerMarks.push(m);
  }
  // Right ruler: spans the FULL sketch height (top to bottom of the drawing,
  // above the bottom length ruler), to the same scale, labelled in cm.
  const vTop = 10;
  const vBot = h - rulerLane - 2;
  const vSpanM = (vBot - vTop) / scale;
  const rulerStepV = niceStep(vSpanM);
  const vTicks: { y: number; label: number }[] = [];
  if (showRuler) for (let m = 0; m <= vSpanM + 1e-6; m += rulerStepV) vTicks.push({ y: vTop + m * scale, label: m });

  return (
    <div ref={wrapRef} style={{ position: 'relative', ...(vertical || fillHeight ? { height: '100%' } : null) }}>
      <svg ref={svgRef} viewBox={vertical ? `0 0 ${h} ${w}` : `0 0 ${w} ${h}`}
          style={vertical
            ? { height: '100%', maxWidth: '100%', display: 'block', margin: '0 auto' }
            : { width: '100%', height: 'auto', display: 'block', touchAction: 'none',
              cursor: zoom.k > 1 ? 'grab' : undefined }}
          role="img"
          aria-label={vertical
            ? 'Rocket side view, nose up, with CG and CP markers'
            : 'Rocket side view with CG and CP markers — drag components, wheel to zoom, drag background to pan'}
          onPointerDownCapture={resetDragLatch}
          onPointerDown={vertical ? undefined : beginPan}
          onPointerMove={vertical ? undefined : onMove}
          onPointerUp={vertical ? undefined : endDrag}
          onPointerLeave={vertical ? undefined : endDrag}>
        <defs>
          {/* Bulkhead fill: the engineering-drawing diagonal hatch. */}
          <pattern id="bulkhead-hatch" patternUnits="userSpaceOnUse" width="5" height="5">
            <path d="M0 5 L5 0" stroke="#66748c" strokeWidth="0.9" />
          </pattern>
        </defs>
        {/* Vertical: one rigid rotation of the horizontal layout — the w×h
            layout rect maps exactly onto the transposed h×w viewBox with the
            nose (layout left) up. rotate(-90) would put it nose DOWN. */}
        <g transform={vertical
          ? `rotate(90 ${h / 2} ${h / 2})`
          : `translate(${zoom.x} ${zoom.y}) scale(${zoom.k})`}>
          {shapes}
          {overlay}
          {/* pointerEvents none on BOTH marker groups: they are decoration
              drawn on the centreline — precisely where you click to select a
              nose cone or body tube — and an 18px opaque disc with no handler
              of its own silently ate the click. Same rule the callout group
              below already follows. */}
          {cgX !== null && (
            <g pointerEvents="none">
              <circle cx={cgX} cy={ctx.cy} r={MARKER_R} fill="var(--surface-1)" stroke="var(--text-primary)" strokeWidth="1.5" />
              <path d={`M ${cgX} ${ctx.cy} L ${cgX + MARKER_R} ${ctx.cy} A ${MARKER_R} ${MARKER_R} 0 0 1 ${cgX} ${ctx.cy + MARKER_R} Z`} fill="var(--text-primary)" />
              <path d={`M ${cgX} ${ctx.cy} L ${cgX - MARKER_R} ${ctx.cy} A ${MARKER_R} ${MARKER_R} 0 0 1 ${cgX} ${ctx.cy - MARKER_R} Z`} fill="var(--text-primary)" />
            </g>
          )}
          {cpX !== null && (
            <g pointerEvents="none">
              <circle cx={cpX} cy={ctx.cy} r={MARKER_R} fill="none" stroke="var(--status-serious)" strokeWidth="2" />
              <circle cx={cpX} cy={ctx.cy} r={3.5} fill="var(--status-serious)" />
            </g>
          )}
          {(callouts.cg || callouts.cp) && (
            <g pointerEvents="none">
              {callouts.cg && (
                <>
                  <line x1={callouts.cg.x} y1={callouts.cg.leaderY1} x2={callouts.cg.x} y2={callouts.cg.leaderY2}
                    stroke="var(--text-primary)" strokeWidth="1" strokeDasharray="4 3" />
                  <circle cx={callouts.cg.x} cy={callouts.cg.leaderY2} r={4} fill="var(--text-primary)" />
                  <text x={callouts.cg.x + 8} y={callouts.cg.leaderY2} dominantBaseline="central"
                    fontSize="11" fontWeight="bold" fill="var(--text-primary)"
                    {...textUp(callouts.cg.x + 8, callouts.cg.leaderY2)}>{cgLabel}</text>
                </>
              )}
              {callouts.cp && (
                <>
                  <line x1={callouts.cp.x} y1={callouts.cp.leaderY1} x2={callouts.cp.x} y2={callouts.cp.leaderY2}
                    stroke="var(--status-serious)" strokeWidth="1" strokeDasharray="4 3" />
                  <circle cx={callouts.cp.x} cy={callouts.cp.leaderY2} r={4} fill="var(--status-serious)" />
                  <text x={callouts.cp.x + 8} y={callouts.cp.leaderY2} dominantBaseline="central"
                    fontSize="11" fontWeight="bold" fill="var(--status-serious)"
                    {...textUp(callouts.cp.x + 8, callouts.cp.leaderY2)}>{cpLabel}</text>
                </>
              )}
              {callouts.margin && stab && (
                <text x={callouts.margin.x} y={callouts.margin.y} textAnchor="middle" dominantBaseline="central"
                  fontSize="11" fontWeight="bold" fill={STABILITY_VAR[stab]}
                  {...textUp(callouts.margin.x, callouts.margin.y)}>{marginText}</text>
              )}
            </g>
          )}
          {hoverBox && hoverTag && (
            <g pointerEvents="none">
              <rect x={hoverBox.x0 - 2} y={hoverBox.y0 - 2}
                width={hoverBox.x1 - hoverBox.x0 + 4} height={hoverBox.y1 - hoverBox.y0 + 4}
                rx="3" fill="var(--accent)" fillOpacity="0.14"
                stroke="var(--accent)" strokeWidth="1" strokeOpacity="0.6" />
              <g {...textUp(hoverTag.x, hoverTag.y)}>
                <rect x={hoverTag.x - hoverTag.tw / 2} y={hoverTag.y - 9}
                  width={hoverTag.tw} height={18} rx="4"
                  fill="rgba(13,14,18,0.9)" stroke="var(--border)" strokeWidth="1" />
                <text x={hoverTag.x} y={hoverTag.y} textAnchor="middle" dominantBaseline="central"
                  fontSize="11" fill="#ffffff">{hoverName}</text>
              </g>
            </g>
          )}
          {caliperH && (() => {
            const ax = ctx.x0 + caliperH.a * scale, bx = ctx.x0 + caliperH.b * scale;
            const top = 4, bot = h - rulerLane - 2, dimY = 14, mid = (ax + bx) / 2;
            return (
              <g>
                {(['a', 'b'] as const).map((k) => {
                  const x = ctx.x0 + caliperH[k] * scale;
                  return (
                    <g key={k}>
                      <line x1={x} y1={top} x2={x} y2={bot} stroke="var(--accent)" strokeWidth="1" strokeDasharray="4 3" vectorEffect="non-scaling-stroke" />
                      <rect x={x - 5} y={top} width={10} height={bot - top} fill="transparent" style={{ cursor: 'ew-resize', pointerEvents: 'all' }} onPointerDown={beginCaliperDrag('h', k)} />
                      <circle cx={x} cy={top + 2} r={3.5} fill="var(--accent)" pointerEvents="none" />
                    </g>
                  );
                })}
                <g pointerEvents="none">
                  <line x1={ax} y1={dimY} x2={bx} y2={dimY} stroke="var(--accent)" strokeWidth="1" vectorEffect="non-scaling-stroke" />
                  <rect x={mid - 28} y={dimY - 9} width={56} height={14} rx="3" fill="rgba(13,14,18,0.92)" stroke="var(--accent)" strokeWidth="0.8" />
                  <text x={mid} y={dimY - 1} textAnchor="middle" fontSize="9" fontWeight="bold" fill="var(--accent)">{fmtNum(Math.abs(caliperH.b - caliperH.a) * 100, 1)} cm</text>
                </g>
              </g>
            );
          })()}
          {caliperV && (() => {
            const ay = ctx.cy - caliperV.a * scale, by = ctx.cy - caliperV.b * scale;
            const left = ctx.x0, right = ctx.x0 + totalLen * scale;
            const dimX = ctx.x0 + 20, mid = (ay + by) / 2;
            return (
              <g>
                {(['a', 'b'] as const).map((k) => {
                  const y = ctx.cy - caliperV[k] * scale;
                  return (
                    <g key={k}>
                      <line x1={left} y1={y} x2={right} y2={y} stroke="var(--accent)" strokeWidth="1" strokeDasharray="4 3" vectorEffect="non-scaling-stroke" />
                      <rect x={left - 4} y={y - 8} width={34} height={16} fill="transparent" style={{ cursor: 'ns-resize', pointerEvents: 'all' }} onPointerDown={beginCaliperDrag('v', k)} />
                      <circle cx={left + 4} cy={y} r={3.5} fill="var(--accent)" pointerEvents="none" />
                    </g>
                  );
                })}
                <g pointerEvents="none">
                  <line x1={dimX} y1={ay} x2={dimX} y2={by} stroke="var(--accent)" strokeWidth="1" vectorEffect="non-scaling-stroke" />
                  <rect x={dimX - 24} y={mid - 7} width={48} height={14} rx="3" fill="rgba(13,14,18,0.92)" stroke="var(--accent)" strokeWidth="0.8" />
                  <text x={dimX} y={mid + 3} textAnchor="middle" fontSize="9" fontWeight="bold" fill="var(--accent)">{fmtNum(Math.abs(caliperV.a - caliperV.b) * 100, 1)}</text>
                </g>
              </g>
            );
          })()}
        </g>
        {showRuler && (() => {
          const base = h - RULER_H + 3, tick = h - RULER_H + 8, label = h - 4;
          return (
            <g pointerEvents="none">
              <line x1={rulerX0} y1={base} x2={rulerX1} y2={base} className="stroke-white/20" />
              {rulerMarks.map((m, i) => {
                const x = ctx.x0 + m * scale;
                return (
                  <g key={i}>
                    <line x1={x} y1={base} x2={x} y2={tick} className="stroke-white/30" />
                    <text x={x} y={label} textAnchor="middle" className="fill-slate-500 text-[7px] tabular-nums">{fmtNum(m * 100, 0)}</text>
                  </g>
                );
              })}
              <text x={rulerX1} y={base - 3} textAnchor="end" className="fill-slate-500 text-[7px]">cm</text>
            </g>
          );
        })()}
        {showRuler && vTicks.length > 0 && (() => {
          const bx = w - RULER_W + 3;
          return (
            <g pointerEvents="none">
              <line x1={bx} y1={vTop} x2={bx} y2={vBot} className="stroke-white/20" />
              {vTicks.map((tk, i) => (
                <g key={i}>
                  <line x1={bx} y1={tk.y} x2={bx - 4} y2={tk.y} className="stroke-white/30" />
                  <text x={bx + 3} y={tk.y} dominantBaseline="central" className="fill-slate-500 text-[7px] tabular-nums">{fmtNum(tk.label * 100, 0)}</text>
                </g>
              ))}
              <text x={bx + 3} y={vTop - 5} className="fill-slate-500 text-[7px]">cm</text>
            </g>
          );
        })()}
      </svg>
      {/* Vertical is read-mostly: no zoom to fit-reset, and the SVG/image
          exports assume the horizontal drawing (identity view transform), so
          the whole strip hides rather than export a sideways page. */}
      {!vertical && (() => {
        const content = (<>
        {exportData && (
          <>
            <button className="file-btn"
              title="True-scale 2D drawing (SVG) with design data — physical mm size, prints at 100% scale"
              onClick={() => {
                if (!svgRef.current) return;
                try {
                  const data = { ...exportData, spanM: 2 * vHalf };
                  downloadBlob(schematicSvg(svgRef.current, scale, w, h, data),
                    `${data.name.replace(/[^\w-]+/g, '_')}-2d.svg`);
                } catch (e) {
                  onError?.(`SVG export failed: ${e instanceof Error ? e.message : String(e)}`);
                }
              }}>
              ⬇ SVG
            </button>
            <ImageExportMenu label="⬇ Image"
              title="High-resolution 2D image with design data — pick PNG or JPG and a width"
              onPick={async (format, widthPx) => {
                if (!svgRef.current) return;
                try {
                  const data = { ...exportData, spanM: 2 * vHalf };
                  const svg = schematicSvg(svgRef.current, scale, w, h, data);
                  downloadBlob(await svgToImage(svg, widthPx, format),
                    `${data.name.replace(/[^\w-]+/g, '_')}-2d.${IMAGE_FORMAT_EXT[format]}`);
                } catch (e) {
                  onError?.(`Image export failed: ${e instanceof Error ? e.message : String(e)}`
                    + ' — try a smaller width, or use ⬇ SVG.');
                }
              }} />
          </>
        )}
        <button className="file-btn" title={t('schematic.calipersH')} aria-pressed={!!caliperH}
          style={caliperH ? { background: 'var(--accent)', color: '#fff' } : undefined}
          onClick={() => setCaliperH((c) => (c ? null : { a: totalLen * 0.2, b: totalLen * 0.8 }))}>
          ⟺
        </button>
        <button className="file-btn" title={t('schematic.calipersV')} aria-pressed={!!caliperV}
          style={caliperV ? { background: 'var(--accent)', color: '#fff' } : undefined}
          onClick={() => setCaliperV((c) => (c ? null : { a: maxR, b: -maxR }))}>
          ⇕
        </button>
        {(zoom.k > 1 || zoom.x !== 0 || zoom.y !== 0) && (
          <button className="file-btn"
            title={t('schematic.fit')}
            onClick={() => setZoom({ k: 1, x: 0, y: 0 })}>
            ⤢ {t('schematic.fit')}
          </button>
        )}
        <button className="file-btn" title={t('schematic.zoomIn')}
          aria-label={t('schematic.zoomIn')} onClick={() => zoomBy(1.5)} disabled={zoom.k >= 12}>+</button>
        <button className="file-btn" title={t('schematic.zoomOut')}
          aria-label={t('schematic.zoomOut')} onClick={() => zoomBy(1 / 1.5)} disabled={zoom.k <= 1}>−</button>
        </>);
        return controlsSlot
          ? createPortal(content, controlsSlot)
          : <div className="schematic-controls">{content}</div>;
      })()}
    </div>
  );
}
