import { useCallback, useEffect, useId, useMemo, useRef, useState } from 'react';
import { createPortal } from 'react-dom';
import { useTranslation } from 'react-i18next';
import type { RocketTree, StaticInfo } from '../../engine/openRocketEngine';
import { useUnits } from '../../prefs/useUnits';
import type { ExportData } from '../../services/schematicExport.js';
import {
  computeSchematicLayout,
  niceRulerStep,
  rulerGraduations,
  RULER_H,
  RULER_W,
  snapNear,
  ZOOM_IDENTITY,
  zoomAbout,
  type MotorDims,
} from './schematicGeometry';
import { buildSchematicShapes } from './schematicShapes';
import { useWheelZoom } from './useWheelZoom';
import { HorizontalCaliper, VerticalCaliper } from './SchematicCalipers';
import { SchematicControls } from './SchematicControls';
import { HoverOverlay, StabilityOverlay } from './SchematicOverlay';
import { LengthRuler, RadialRuler } from './SchematicRulers';

/**
 * 2D side view generated by walking the component tree. Symmetric top-level
 * components (nose/transition/body) form the axial chain; children draw on
 * or inside their parent at their resolved axial position and can be DRAGGED
 * axially (snapping to structural anchors — tube ends, sibling edges).
 * Clustered inner tubes draw one outline per cluster position.
 * CG/CP markers use standard rocketry symbols.
 *
 * This file is the composition: the view state (size, hover, zoom, calipers,
 * pan) and the pointer handlers that drive it. The pieces it composes are the
 * part outlines (schematicShapes), the CG/CP markers and hover tag
 * (SchematicOverlay), the calipers (SchematicCalipers), the measuring frame
 * (SchematicRulers) and the button strip (SchematicControls).
 */

/** Client px a press may wander before it counts as a pan rather than a click.
 *  Matches the drag threshold in onMove — a physical click jitters 1-3 px. */
const PAN_SLOP = 4;

/** Every ruler on. Module scope, not a default-parameter literal: `rulers` is a
 *  dependency of the layout memo, and a fresh object per render defeated it
 *  for every caller that left the prop off. */
const DEFAULT_RULERS = { top: true, bottom: true, left: true, right: true };
/** Wheel step and zoom ceiling; hoisted so the hook's options keep one identity. */
const WHEEL_ZOOM = { factor: 1.2, max: 12 };

export function TreeSchematic({
  tree,
  info,
  motors,
  maxHeight = 480,
  selectedId,
  onSelect,
  exportData,
  onError,
  vertical,
  fillHeight,
  roll = 0,
  onRoll,
  controlsSlot,
  showMarkers = true,
  rulers = DEFAULT_RULERS,
}: {
  tree: RocketTree;
  info: StaticInfo | null;
  /** Loaded motor case dimensions (m) keyed by mount node id — drawn to
   *  scale; `label` is the designation printed in the case when it fits (S5). */
  motors?: MotorDims;
  /** Cap on the drawing's on-screen height (px). */
  maxHeight?: number;
  /** Two-way selection sync with the component tree (2026-08-05b #21). */
  selectedId?: string | null;
  onSelect?: (id: string) => void;
  /** When set, ⬇ SVG / ⬇ PNG export buttons appear (issue 2026-08-11a). */
  exportData?: Omit<ExportData, 'spanM'>;
  /**
   * Reports an export failure to the caller's note channel. Rasterizing really
   * can fail — svgToImage rejects from img.onerror, and a big rocket at 7680px
   * can exhaust the canvas — and the awaited rejection used to go nowhere: the
   * button just did nothing, which reads as "the export is broken" with
   * nothing to report.
   */
  onError?: (message: string) => void;
  /** Nose-up view (S1 rotate / S4 phone): the horizontal layout rotates as
   *  one group to fit the container's HEIGHT. Read-mostly — drag, pan, zoom
   *  and the export/zoom controls are off; hover and click-select stay. */
  vertical?: boolean;
  /** Hero canvas (batch 08-21e): the drawing surface spans the container's
   *  FULL height instead of the adaptive content height — otherwise the svg's
   *  invisible clip edges sit mid-canvas and a zoomed rocket "slides under"
   *  what reads as a black box. Ignored in vertical mode (which fills by its
   *  own rule); overrides maxHeight. */
  fillHeight?: boolean;
  /** Roll angle (radians) about the rocket's long axis — spins the fin sets so
   *  each fin projects by cos(roll + i·2π/N), like OpenRocket's rotation. */
  roll?: number;
  /** When set, a horizontal drag on the drawing spins the roll (delta radians)
   *  instead of panning — so the user can drag to rotate the rocket. */
  onRoll?: (deltaRadians: number) => void;
  /** When set, the drawing's control buttons (calipers, zoom, export) render into
   *  this element (a slot in the pane header) instead of over the drawing. */
  controlsSlot?: HTMLElement | null;
  /** Draw the CG/CP/margin markers and callouts (default true). */
  showMarkers?: boolean;
  /** Which sides of the side view are framed by a measurement ruler (default all). */
  rulers?: { top: boolean; bottom: boolean; left: boolean; right: boolean };
}) {
  const svgRef = useRef<SVGSVGElement>(null);
  const wrapRef = useRef<HTMLDivElement>(null);
  // Container width (CSS px). The viewBox adopts it 1:1, so the drawing fills
  // the column at native pixel scale on any monitor instead of a fixed 640px
  // canvas stretched to fit.
  const [cw, setCw] = useState(640);
  // Container height (CSS px) — the length axis in vertical mode. Stays at
  // the fallback when the wrap has no definite height to inherit.
  const [chPx, setChPx] = useState(480);
  // Hovered component (S5): accent wash + name tag drawn topmost. Enter/
  // leave never fire from touch, so phones skip hover naturally.
  const [hoverId, setHoverId] = useState<string | null>(null);
  // View transform (zoom & pan) in viewBox px; identity = whole rocket fits.
  const [zoom, setZoom] = useState(ZOOM_IDENTITY);
  // Calipers (measure tool): horizontal (two vertical lines, model x) and/or
  // vertical (two horizontal lines, radial offset from the centerline). null = off.
  const [caliperH, setCaliperH] = useState<{ a: number; b: number } | null>(null);
  const [caliperV, setCaliperV] = useState<{ a: number; b: number } | null>(null);
  const caliperDrag = useRef<{ axis: 'h' | 'v'; end: 'a' | 'b' } | null>(null);
  const { t } = useTranslation();
  const u = useUnits();
  // `active` only becomes true once the pointer has traveled past PAN_SLOP —
  // see beginPan for why a press must not pan until then.
  const pan = useRef<{ pointerX: number; pointerY: number; x0: number; y0: number; active: boolean } | null>(null);

  // --- measure the axial chain (memoized) ---
  // Pure geometry derived from the tree, info and container size, so the
  // frequently-changing state (hover, zoom, calipers, roll) no longer
  // recomputes the whole layout on every render.
  const layout = useMemo(
    () => computeSchematicLayout(tree, info, { vertical, chPx, cw, maxHeight, fillHeight, rulers }),
    [tree, info, vertical, chPx, cw, maxHeight, fillHeight, rulers],
  );
  const { chain, totalLen, maxR, vHalf, snapXs, radialSnaps, rTop, rBot, w, h, scale, ctx } = layout;

  /**
   * Arms a background pan — but does NOT start one, and deliberately does not
   * capture the pointer yet.
   *
   * This handler runs for every press that reaches the svg, which is every
   * press on the axial chain (nose cone, body tube, transition). It used to pan on the
   * very first pointermove and capture the pointer immediately, so the 1-3 px
   * of jitter in an ordinary physical click dragged the whole drawing out from
   * under the pointer between press and release. The click then landed on the
   * <svg> instead of the shape and selecting those parts did nothing at all —
   * while children stayed fine, and the vertical view (which attaches neither
   * handler) worked perfectly. Capturing on press made it worse by retargeting
   * the release as well.
   *
   * Both now wait for real movement, so a click stays a click.
   */
  const beginPan = (e: React.PointerEvent) => {
    const rect = svgRef.current?.getBoundingClientRect();
    if (!rect || rect.width === 0) return;
    pan.current = { pointerX: e.clientX, pointerY: e.clientY, x0: zoom.x, y0: zoom.y, active: false };
  };

  /** Screen clientX → model x (meters), through the current pan/zoom. */
  const clientToModelX = (clientX: number): number => {
    const rect = svgRef.current?.getBoundingClientRect();
    if (!rect || !rect.width) return 0;
    const viewBoxX = ((clientX - rect.left) / rect.width) * w;
    return ((viewBoxX - zoom.x) / zoom.k - ctx.x0) / scale;
  };
  /** Screen clientY → radial offset from the centerline (meters, + up). */
  const clientToModelY = (clientY: number): number => {
    const rect = svgRef.current?.getBoundingClientRect();
    if (!rect || !rect.height) return 0;
    const viewBoxY = ((clientY - rect.top) / rect.height) * h;
    return (ctx.cy - (viewBoxY - zoom.y) / zoom.k) / scale;
  };

  const beginCaliperDrag = (axis: 'h' | 'v', end: 'a' | 'b') => (e: React.PointerEvent) => {
    e.stopPropagation(); // don't also start a pan
    caliperDrag.current = { axis, end };
    (e.currentTarget as Element).setPointerCapture?.(e.pointerId);
  };

  /**
   * Keyboard nudging for a caliper handle.
   *
   * The handles were bare `<rect onPointerDown>` with no tabIndex, role or key
   * handler, and the measurement is only rendered inside the SVG - so the
   * app's one way to read a distance off the drawing was unusable without a
   * pointer. Siblings in this very directory were given keyboard paths for
   * exactly this reason (AeroAnalysis, FlightChart, FreeformFinEditor).
   *
   * Arrows nudge by 1 mm, Shift by 10 mm, Home/End jump to the ends. Values
   * are clamped the same way the drag path clamps them.
   */
  const caliperKeys = (axis: 'h' | 'v', end: 'a' | 'b') => (e: React.KeyboardEvent) => {
    const step = (e.shiftKey ? 0.01 : 0.001) * (e.key === 'ArrowLeft' || e.key === 'ArrowDown' ? -1 : 1);
    const isArrow = ['ArrowLeft', 'ArrowRight', 'ArrowUp', 'ArrowDown'].includes(e.key);
    if (!isArrow && e.key !== 'Home' && e.key !== 'End') return;
    e.preventDefault();
    e.stopPropagation();
    if (axis === 'h') {
      setCaliperH((c) => {
        if (!c) return c;
        const next = e.key === 'Home' ? 0 : e.key === 'End' ? totalLen : c[end] + step;
        return { ...c, [end]: Math.max(0, Math.min(totalLen, next)) };
      });
    } else {
      setCaliperV((c) => {
        if (!c) return c;
        const next = e.key === 'Home' ? -vHalf : e.key === 'End' ? vHalf : c[end] + step;
        return { ...c, [end]: Math.max(-vHalf, Math.min(vHalf, next)) };
      });
    }
  };

  const onMove = (e: React.PointerEvent) => {
    if (caliperDrag.current) {
      const { axis, end } = caliperDrag.current;
      const eps = 6 / (scale * zoom.k); // ~6 screen px of snap magnetism
      if (axis === 'h') {
        const mx = Math.max(0, Math.min(totalLen, snapNear(clientToModelX(e.clientX), snapXs, eps)));
        setCaliperH((c) => (c ? { ...c, [end]: mx } : c));
      } else {
        const raw = clientToModelY(e.clientY);
        const mag = snapNear(Math.abs(raw), radialSnaps, eps);
        const my = Math.max(-vHalf, Math.min(vHalf, Math.sign(raw || 1) * mag));
        setCaliperV((c) => (c ? { ...c, [end]: my } : c));
      }
      return;
    }
    const p = pan.current;
    if (p) {
      const dx = e.clientX - p.pointerX;
      const dy = e.clientY - p.pointerY;
      // Below the slop this press is still a click, not a pan. Once it IS a
      // pan, take the pointer so the gesture survives leaving the svg.
      if (!p.active) {
        if (Math.abs(dx) < PAN_SLOP && Math.abs(dy) < PAN_SLOP) return;
        p.active = true;
        (e.currentTarget as Element).setPointerCapture?.(e.pointerId);
      }
      // Drag-to-roll: horizontal motion spins the fins (~1 turn per width).
      if (onRoll) {
        const r = svgRef.current?.getBoundingClientRect();
        const width = r && r.width ? r.width : 400;
        onRoll((dx / width) * 2 * Math.PI);
        p.pointerX = e.clientX;
        return;
      }
      const rect = svgRef.current?.getBoundingClientRect();
      if (!rect || rect.width === 0) return;
      const clientScale = w / rect.width;
      setZoom((z) => ({ ...z, x: p.x0 + dx * clientScale, y: p.y0 + dy * clientScale }));
    }
  };

  const endDrag = () => {
    pan.current = null;
    caliperDrag.current = null;
  };

  // Track the container's size so the viewBox can follow it (height feeds
  // the vertical mode's length axis).
  useEffect(() => {
    const el = wrapRef.current;
    if (!el) return;
    const obs = new ResizeObserver(() => {
      if (el.clientWidth > 0) setCw(el.clientWidth);
      if (el.clientHeight > 0) setChPx(el.clientHeight);
    });
    obs.observe(el);
    return () => obs.disconnect();
  }, []);

  // Wheel zoom around the pointer (shared hook; the vertical view is read-only).
  const wheelToView = useCallback(
    (e: WheelEvent, rect: DOMRect) => ({
      px: ((e.clientX - rect.left) / rect.width) * w,
      py: ((e.clientY - rect.top) / rect.height) * h,
    }),
    [w, h],
  );
  useWheelZoom(svgRef, setZoom, vertical ? null : wheelToView, WHEEL_ZOOM);

  // Button zoom steps around the view center (the wheel handles precise
  // pointer-anchored zoom; these make the capability visible).
  const zoomBy = (f: number) =>
    setZoom((z) => zoomAbout(z, w / 2, h / 2, Math.min(WHEEL_ZOOM.max, Math.max(1, z.k * f))));

  // Nose-up rendering rotates the whole drawing; every text label counter-
  // rotates about its own anchor so it still reads horizontally.
  const textUp = useCallback(
    (x: number, y: number) => (vertical ? { transform: `rotate(-90 ${x} ${y})` } : {}),
    [vertical],
  );

  // Namespaces this instance's clipPath ids so two schematics sharing a document
  // can't cross-clip (url(#id) resolves to the first match in the document).
  const uid = useId().replace(/:/g, '');
  // Unnamed parts print the tree panel's translated type name, not the schema's
  // English label, so the hover tag and <title> read the same as the tree.
  const partName = useCallback((n: { type: string }) => t(`part.${n.type}`), [t]);
  // The whole SVG scene — every part outline, wire, clip path and clip def.
  // It ran unmemoized in the render body, so it was rebuilt from scratch on
  // every unrelated state change in this component (caliper drag, ruler
  // toggle, tooltip, pan) as well as on every parent re-render, for a design
  // that had not moved. The hovered id is deliberately NOT an input: the
  // build returns every part's extent, and the hover decoration is resolved
  // from that map below, so entering and leaving a part costs a Map lookup
  // rather than a full rebuild.
  const { shapes, overlay, wires, clipDefs, extents } = useMemo(
    () =>
      buildSchematicShapes({
        chain,
        ctx,
        scale,
        w,
        h,
        roll,
        uid,
        motors,
        vertical,
        selectedId,
        onSelect,
        setHoverId,
        partName,
        textUp,
      }),
    [chain, ctx, scale, w, h, roll, uid, motors, vertical, selectedId, onSelect, partName, textUp],
  );
  // The hovered part's extent, resolved from the memoized map (see above).
  const hovered = hoverId ? extents.get(hoverId) : undefined;

  // Dimension ruler (side view, only at the default fit): nice-round marks every
  // `rulerStep` meters, labeled in cm. 0 sits at the nose (the datum) but the
  // baseline + ticks run the FULL viewport width, so it reads as a workbench
  // rule spanning the canvas rather than a bar clipped to the airframe.
  // Rulers only at the default fit (a pan/zoom would slide them off scale). Each
  // side is toggled independently; length (top/bottom) and radial (left/right)
  // marks are computed if either ruler of that pair is on.
  const rulersActive = !vertical && zoom.k === 1 && zoom.x === 0 && zoom.y === 0;
  const showLen = rulersActive && (rulers.top || rulers.bottom);
  const showRad = rulersActive && (rulers.left || rulers.right);
  // Labeled majors are DENSE: aim for one roughly every ~12 screen px (rounded
  // to a nice 1/2/5 mm step), so the scale reads like a real drafting ruler
  // (a number every ~10 mm) rather than a handful of marks across the canvas.
  const rulerStepUi = niceRulerStep(u.toUi('length', (8 * 22) / scale));
  const rulerStep = u.fromUi('length', rulerStepUi);
  // Enough decimals to tell one graduation from the next, and no more.
  const rulerDigits = rulerStepUi >= 1 ? 0 : rulerStepUi >= 0.1 ? 1 : 2;
  // Each ruler stops a few px short of the corner where it would meet another,
  // so the frame reads as four separate rules rather than one welded box. A
  // ruler that instead runs to the viewport edge (its neighbor is off) keeps no
  // gap there — nothing to separate from.
  const CORNER_GAP = 5;
  const rulerX0 = rulers.left ? RULER_W - 4 + CORNER_GAP : 2;
  const rulerX1 = rulers.right ? w - RULER_W + 4 - CORNER_GAP : w - 2;
  const frameTopY = rulers.top ? RULER_H - 4 + CORNER_GAP : 2;
  const frameBotY = rulers.bottom ? h - RULER_H + 4 - CORNER_GAP : h - 2;
  // Radial rulers span the drawing height between the top/bottom lanes, to the
  // same scale, labeled in mm.
  const vTop = rTop + 4;
  const vBot = h - rBot - 4;
  const vSpanM = (vBot - vTop) / scale;
  /**
   * The graduations, memoized.
   *
   * Minor ticks run every `rulerStep / 5` across the whole viewport - 150 to
   * 300 entries typically - and all four arrays were rebuilt in the render
   * body, so every hover and every selection change regenerated them and
   * re-rendered that many SVG nodes. This file already memoizes the far more
   * expensive `buildSchematicShapes` for exactly this reason; the rulers were
   * the remaining unmemoized derivation, and they are on by default.
   *
   * The datum is read out of `ctx` first so the memo is keyed on the number:
   * keyed on `ctx.x0` inside the closure, the compiler inferred `ctx` as the
   * dependency and refused to preserve the memo.
   */
  const x0 = ctx.x0;
  const { rulerMarks, vTicks, rulerMinorMarks, vMinorTicks } = useMemo(
    () => rulerGraduations({ showLen, showRad, rulerStep, rulerX0, rulerX1, x0, scale, vSpanM, vTop }),
    [showLen, showRad, rulerStep, rulerX0, rulerX1, x0, scale, vSpanM, vTop],
  );
  // The values every ruler of one kind shares; the per-edge placement is
  // passed at the call site below.
  const lengthRulerProps = { x0: rulerX0, x1: rulerX1, ctxX0: x0, scale, rulerStep, rulerDigits };
  const radialRulerProps = { frameTopY, frameBotY, vTop, scale, rulerStep, rulerDigits };

  // The drawing's control strip. Vertical is read-mostly: no zoom to
  // fit-reset, and the SVG/image exports assume the horizontal drawing
  // (identity view transform), so the whole strip hides rather than export a
  // sideways page.
  const controls = vertical ? null : (
    <SchematicControls
      svgRef={svgRef}
      exportData={exportData}
      onError={onError}
      scale={scale}
      w={w}
      h={h}
      vHalf={vHalf}
      totalLen={totalLen}
      maxR={maxR}
      caliperH={caliperH}
      caliperV={caliperV}
      setCaliperH={setCaliperH}
      setCaliperV={setCaliperV}
      zoom={zoom}
      setZoom={setZoom}
      zoomBy={zoomBy}
    />
  );

  return (
    <div ref={wrapRef} style={{ position: 'relative', ...(vertical || fillHeight ? { height: '100%' } : null) }}>
      <svg
        ref={svgRef}
        viewBox={vertical ? `0 0 ${h} ${w}` : `0 0 ${w} ${h}`}
        style={
          vertical
            ? { height: '100%', maxWidth: '100%', display: 'block', margin: '0 auto' }
            : {
                width: '100%',
                height: 'auto',
                display: 'block',
                touchAction: 'none',
                cursor: zoom.k > 1 ? 'grab' : undefined,
              }
        }
        // role="img" ONLY for the read-only nose-up view: on the editable view it
        // would tell assistive tech the whole SVG is a single static image and
        // hide every clickable component. (Keyboard selection lives in the
        // component tree, which is now focusable.)
        role={vertical ? 'img' : undefined}
        aria-label={vertical ? t('schematic.sideAriaVertical') : t('schematic.sideAria')}
        onPointerDown={vertical ? undefined : beginPan}
        onPointerMove={vertical ? undefined : onMove}
        onPointerUp={vertical ? undefined : endDrag}
        onPointerLeave={vertical ? undefined : endDrag}
      >
        <defs>
          {/* Bulkhead fill: the engineering-drawing diagonal hatch. */}
          <pattern id="bulkhead-hatch" patternUnits="userSpaceOnUse" width="5" height="5">
            <path d="M0 5 L5 0" stroke="#66748c" strokeWidth="0.9" />
          </pattern>
          {/* Airframe-band cuts: clip a far fin's fill at the tube wall. */}
          {clipDefs}
        </defs>
        {/* Vertical: one rigid rotation of the horizontal layout — the w×h
            layout rect maps exactly onto the transposed h×w viewBox with the
            nose (layout left) up. rotate(-90) would put it nose DOWN. */}
        <g transform={vertical ? `rotate(90 ${h / 2} ${h / 2})` : `translate(${zoom.x} ${zoom.y}) scale(${zoom.k})`}>
          {shapes}
          {overlay}
          {/* Wireframe fin outlines while the view is rolled (paint topmost). */}
          {wires}
          <StabilityOverlay
            info={info}
            showMarkers={showMarkers}
            ctx={ctx}
            scale={scale}
            vHalf={vHalf}
            w={w}
            h={h}
            textUp={textUp}
          />
          <HoverOverlay box={hovered?.box ?? null} name={hovered?.name ?? ''} w={w} h={h} textUp={textUp} />
          {caliperH && (
            <HorizontalCaliper
              cal={caliperH}
              ctx={ctx}
              scale={scale}
              h={h}
              rBot={rBot}
              totalLen={totalLen}
              onDragStart={(end) => beginCaliperDrag('h', end)}
              onKey={(end) => caliperKeys('h', end)}
            />
          )}
          {caliperV && (
            <VerticalCaliper
              cal={caliperV}
              ctx={ctx}
              scale={scale}
              totalLen={totalLen}
              vHalf={vHalf}
              onDragStart={(end) => beginCaliperDrag('v', end)}
              onKey={(end) => caliperKeys('v', end)}
            />
          )}
        </g>
        {/* Length rulers frame the top + bottom edges; radial rulers the left +
            right — each drawn only when that side is toggled on (see
            SchematicRulers). */}
        {rulersActive && rulers.bottom && (
          <LengthRuler
            {...lengthRulerProps}
            baseY={h - RULER_H + 4}
            dir={1}
            labelY={h - 3}
            unitY={h - 3}
            marks={rulerMarks}
            minorMarks={rulerMinorMarks}
          />
        )}
        {rulersActive && rulers.top && (
          <LengthRuler
            {...lengthRulerProps}
            baseY={RULER_H - 4}
            dir={-1}
            labelY={11}
            unitY={11}
            marks={rulerMarks}
            minorMarks={rulerMinorMarks}
          />
        )}
        {rulersActive && rulers.right && vTicks.length > 0 && (
          <RadialRuler
            {...radialRulerProps}
            baseX={w - RULER_W + 4}
            dir={1}
            labelX={w - RULER_W + 20}
            anchor="start"
            ticks={vTicks}
            minorTicks={vMinorTicks}
          />
        )}
        {rulersActive && rulers.left && vTicks.length > 0 && (
          <RadialRuler
            {...radialRulerProps}
            baseX={RULER_W - 4}
            dir={-1}
            labelX={RULER_W - 20}
            anchor="end"
            ticks={vTicks}
            minorTicks={vMinorTicks}
          />
        )}
      </svg>
      {/* Vertical is read-mostly: no zoom to fit-reset, and the SVG/image
          exports assume the horizontal drawing (identity view transform), so
          the whole strip hides rather than export a sideways page. */}
      {controls &&
        (controlsSlot ? createPortal(controls, controlsSlot) : <div className="schematic-controls">{controls}</div>)}
    </div>
  );
}
