// @vitest-environment jsdom
import { describe, expect, it } from 'vitest';
import { zipSync, strToU8 } from 'fflate';
import { unpackOrk } from '../../src/services/ork/importUnpack';
import { importOrk } from '../../src/services/orkFile';
import { parseRse } from '../../src/services/rseParser';

/**
 * The members of a `.ork` archive other than its XML.
 *
 * A `.ork` is a zip of up to four kinds of member, and we used to take the XML
 * and drop the rest. One of those dropped members has teeth: OpenRocket embeds
 * the thrust curve of every motor a design uses, precisely so the file opens on
 * an install that does not have them, and without it a design using anything
 * outside our catalog opened with an empty mount and a blocked run.
 *
 * jsdom, because importing a design parses XML.
 */

const XML = `<?xml version='1.0' encoding='utf-8'?>
<openrocket version="1.9" creator="OpenRocket 24.12">
  <rocket>
    <name>Archive test</name>
    <subcomponents>
      <stage>
        <name>Sustainer</name>
        <subcomponents>
          <bodytube>
            <name>Body tube</name>
            <length>0.3</length>
            <thickness>0.001</thickness>
            <outerradius>0.026</outerradius>
          </bodytube>
        </subcomponents>
      </stage>
    </subcomponents>
  </rocket>
</openrocket>`;

/** A small but real RockSim engine file, the form the desktop embeds. */
const RSE = `<engine-database>
 <engine-list>
  <engine code="J350" mfg="AeroTech" Type="single-use" dia="38." len="326."
          initWt="878." propWt="496." Itot="712.9" avgThrust="350." peakThrust="480."
          burn-time="2.04" delays="6,10,14" massFrac="56." exitDia="0." Isp="146.">
   <data>
    <eng-data t="0." f="0." m="496." cg="163."/>
    <eng-data t="0.1" f="420." m="470." cg="163."/>
    <eng-data t="1.0" f="380." m="250." cg="163."/>
    <eng-data t="2.04" f="0." m="0." cg="163."/>
   </data>
  </engine>
 </engine-list>
</engine-database>`;

const archive = (members: Record<string, string>): ArrayBuffer => {
  const zipped = zipSync(Object.fromEntries(Object.entries(members).map(([k, v]) => [k, strToU8(v)])));
  // A fresh buffer, so the view's own offsets cannot matter to the caller.
  return zipped.slice().buffer as ArrayBuffer;
};

describe('unpacking the archive', () => {
  it('finds the XML and the thrust curves, and says what it kept nothing from', () => {
    const out = unpackOrk(
      archive({
        'rocket.ork': XML,
        'thrustcurves/abc123.rse': RSE,
        'decals/flames.png': 'not really a png',
        'preview.png': 'not really a png either',
      }),
    );
    expect(out.xml).toContain('<openrocket');
    expect(out.motorFiles).toHaveLength(1);
    expect(out.motorFiles[0]).toContain('J350');
    // The thumbnail is regenerated by whatever opens the file next, so it is not
    // worth telling anyone about. The decal image is.
    expect(out.dropped).toEqual(['decals/flames.png']);
  });

  it('takes a `.rse` wherever it sits, not only under thrustcurves/', () => {
    // The folder is the desktop's convention, not something its loader needs.
    const out = unpackOrk(archive({ 'rocket.ork': XML, 'J350.rse': RSE }));
    expect(out.motorFiles).toHaveLength(1);
  });

  it('reads a bare-XML .ork as the whole file, with nothing else in it', () => {
    const out = unpackOrk(XML);
    expect(out.xml).toBe(XML);
    expect(out.motorFiles).toEqual([]);
    expect(out.dropped).toEqual([]);
  });
});

describe('what the import result carries', () => {
  it('passes the embedded curves along', () => {
    const res = importOrk(archive({ 'rocket.ork': XML, 'thrustcurves/abc123.rse': RSE }));
    expect(res.embeddedMotors).toHaveLength(1);
    // Parsed here rather than by the importer: the ork reader's business is the
    // design, and `loadOrk` is what needs a motor.
    const motors = parseRse(res.embeddedMotors![0]!);
    expect(motors[0]!.designation).toContain('J350');
    expect(motors[0]!.samples.length).toBeGreaterThan(2);
  });

  it('leaves the field off entirely when the file carried none', () => {
    expect(importOrk(XML).embeddedMotors).toBeUndefined();
  });

  it('names a dropped member in the notes', () => {
    const res = importOrk(archive({ 'rocket.ork': XML, 'decals/flames.png': 'x' }));
    expect(res.notes.join('\n')).toContain('decals/flames.png');
  });

  it('says nothing about the thumbnail, which is regenerated anyway', () => {
    const res = importOrk(archive({ 'rocket.ork': XML, 'preview.png': 'x' }));
    expect(res.notes.join('\n')).not.toContain('preview.png');
  });
});
